### PR TITLE
Sort by Bolt and change default sort

### LINKED ISSUE #72: Sort by Bolt
Currently the sort method does not work on the bolt command. Lets fix this

### PR DESCRIPTION
**Pull request by laksherthanlife**
Lets allow for sorting to work for bolt as well. lets also ensure that each time a student is added,removed or edited in classmonitor, the students displayed will default to sorted in ascending order of name. in the case of breaking ties after sorting, ascending order of names will also be used. fixes #72

### CODE REVIEW

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -142,7 +144,7 @@ public void updateSortedStudentListByField(String field, boolean isAscending) {
         Comparator<Student> comparator;
         switch (field.toLowerCase()) {
         case "email":
-            comparator = Comparator.comparing(Student::getEmail);
+            comparator = Comparator.comparing(Student::getEmail).thenComparing(Student::getName);
```
Comment (evedaktyl) [inline src/main/java/seedu/address/model/ModelManager.java]: Is this necessary?

**Review by evedaktyl — COMMENTED** [review]
Lgtm, just a minor fix suggested

File: src/main/java/seedu/address/model/ModelManager.java (hunk 1 above)
Comment (laksherthanlife) [reply src/main/java/seedu/address/model/ModelManager.java]: agreed its not needed. good catch!
